services:
  db:
    image: postgres:16
    container_name: periodic_table_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: periodic_table
    volumes:
      - ./periodic_table.sql:/docker-entrypoint-initdb.d/periodic_table.sql
      - pgdata:/var/lib/postgresql/data

  sandman:
    image: jeffknupp/sandman2
    container_name: sandman2_api
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_DRIVER: psycopg2
      USERNAME: postgres
      PASSWORD: postgres
      DATABASE: periodic_table
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "9000:5000"
    restart: always

volumes:
  pgdata:

